/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ApplicationStart.java
 *
 * Created on Oct 12, 2011, 8:27:01 PM
 */
package userinterface;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.*;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeEvent;
import org.openide.awt.TabbedPaneFactory;

/**
 *
 * @author Brittany Nkounkou
 */
public class MainFrame extends JFrame implements PropertyChangeListener{

    /** Creates new form ApplicationStart */
    public MainFrame() {
        helpViewIndex = -1;
        searchBoxEmpty = true;
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int w = (int) screenSize.getWidth();
        int h = (int) screenSize.getHeight();
        setBounds(w/10, h/10, w*4/5, h*3/4);
        projectData.requestFocusInWindow();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        project = new javax.swing.JSplitPane();
        projectData = new javax.swing.JSplitPane();
        repository = new javax.swing.JScrollPane();
        sourceFolder = new javax.swing.JTree();
        tags = new javax.swing.JTabbedPane();
        viewAllTags = new javax.swing.JScrollPane();
        allTags = new javax.swing.JTree();
        editMyTags = new javax.swing.JScrollPane();
        myTags = new javax.swing.JTree();
        views = TabbedPaneFactory.createCloseButtonTabbedPane();
        searchBox = new javax.swing.JTextField();
        applicationMenu = new javax.swing.JMenuBar();
        projectMenu = new javax.swing.JMenu();
        newProject = new javax.swing.JMenuItem();
        openProject = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        saveProject = new javax.swing.JMenuItem();
        saveAsProject = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mergeProject = new javax.swing.JMenuItem();
        viewVersionHistory = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        manageUsers = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        closeProject = new javax.swing.JMenuItem();
        userMenu = new javax.swing.JMenu();
        editUser = new javax.swing.JMenuItem();
        signOutUser = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        helpContents = new javax.swing.JMenuItem();
        about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AppName");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(500, 300));
        setName(""); // NOI18N

        project.setDividerLocation(200);

        projectData.setDividerLocation(250);
        projectData.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        repository.setViewportView(sourceFolder);

        projectData.setTopComponent(repository);

        viewAllTags.setViewportView(allTags);

        tags.addTab("View All Tags", viewAllTags);

        editMyTags.setViewportView(myTags);

        tags.addTab("Edit My Tags", editMyTags);

        projectData.setRightComponent(tags);

        project.setLeftComponent(projectData);

        views.addPropertyChangeListener(TabbedPaneFactory.PROP_CLOSE, this);
        project.setRightComponent(views);

        searchBox.setForeground(new java.awt.Color(153, 153, 153));
        searchBox.setText("Search");
        searchBox.setMaximumSize(new java.awt.Dimension(250, 27));
        searchBox.setMinimumSize(new java.awt.Dimension(250, 27));
        searchBox.setPreferredSize(new java.awt.Dimension(250, 27));
        searchBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBoxActionPerformed(evt);
            }
        });
        searchBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchBoxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchBoxFocusLost(evt);
            }
        });

        projectMenu.setText("Project");
        projectMenu.setFocusCycleRoot(true);
        projectMenu.setFocusPainted(true);

        newProject.setText("New");
        projectMenu.add(newProject);

        openProject.setText("Open");
        projectMenu.add(openProject);
        projectMenu.add(jSeparator1);

        saveProject.setText("Save");
        projectMenu.add(saveProject);

        saveAsProject.setText("Save As");
        projectMenu.add(saveAsProject);
        projectMenu.add(jSeparator3);

        mergeProject.setText("Merge");
        projectMenu.add(mergeProject);

        viewVersionHistory.setText("View Version History");
        projectMenu.add(viewVersionHistory);
        projectMenu.add(jSeparator4);

        manageUsers.setText("Manage Users");
        projectMenu.add(manageUsers);
        projectMenu.add(jSeparator2);

        closeProject.setText("Close");
        projectMenu.add(closeProject);

        applicationMenu.add(projectMenu);

        userMenu.setText("User");
        userMenu.setFocusCycleRoot(true);
        userMenu.setFocusPainted(true);

        editUser.setText("Edit Account");
        userMenu.add(editUser);

        signOutUser.setText("Sign Out");
        userMenu.add(signOutUser);
        signOutUser.getAccessibleContext().setAccessibleName("");

        applicationMenu.add(userMenu);

        helpMenu.setText("Help");
        helpMenu.setFocusCycleRoot(true);
        helpMenu.setFocusPainted(true);

        helpContents.setText("Help Contents");
        helpContents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpContentsActionPerformed(evt);
            }
        });
        helpMenu.add(helpContents);

        about.setText("About");
        helpMenu.add(about);

        applicationMenu.add(helpMenu);

        applicationMenu.add(Box.createHorizontalGlue());
        applicationMenu.add(searchBox);

        setJMenuBar(applicationMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(project, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(project, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void helpContentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpContentsActionPerformed
    if (helpViewIndex == -1) {
        addView(new HelpView());
        helpViewIndex = views.getSelectedIndex();
    }
    else {
        views.setSelectedIndex(helpViewIndex);
    }
    views.getSelectedComponent().requestFocusInWindow();
}//GEN-LAST:event_helpContentsActionPerformed

private void searchBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchBoxFocusGained
    if (searchBoxEmpty) {
        searchBox.setText("");
        searchBox.setForeground(Color.BLACK);
    }
}//GEN-LAST:event_searchBoxFocusGained

private void searchBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchBoxFocusLost
    if (searchBox.getText().equals("")) {
        searchBoxEmpty = true;
        searchBox.setText("");
        searchBox.setForeground(new Color(153, 153, 153));
        searchBox.setText("Search");
    }
    else {
        searchBoxEmpty = false;
    }
}//GEN-LAST:event_searchBoxFocusLost

private void searchBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBoxActionPerformed
    String text = searchBox.getText();
    if (!text.equals("")) {
        addView(new SearchView("Search \""+text+"\""));
    }
    views.getSelectedComponent().requestFocusInWindow();
}//GEN-LAST:event_searchBoxActionPerformed

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        int indexToDelete = views.indexOfComponent((java.awt.Component)evt.getNewValue());
        if (helpViewIndex == indexToDelete) {
            helpViewIndex = -1;
        }
        views.removeTabAt(indexToDelete);
    }

    public void addView(View v) {
        views.addTab(v.getAbbrv(), null, v, v.getTitle());
        views.setSelectedIndex(views.indexOfComponent(v));
    }
    
    private int helpViewIndex;
    private boolean searchBoxEmpty;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem about;
    private javax.swing.JTree allTags;
    private javax.swing.JMenuBar applicationMenu;
    private javax.swing.JMenuItem closeProject;
    private javax.swing.JScrollPane editMyTags;
    private javax.swing.JMenuItem editUser;
    private javax.swing.JMenuItem helpContents;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenuItem manageUsers;
    private javax.swing.JMenuItem mergeProject;
    private javax.swing.JTree myTags;
    private javax.swing.JMenuItem newProject;
    private javax.swing.JMenuItem openProject;
    private javax.swing.JSplitPane project;
    private javax.swing.JSplitPane projectData;
    private javax.swing.JMenu projectMenu;
    private javax.swing.JScrollPane repository;
    private javax.swing.JMenuItem saveAsProject;
    private javax.swing.JMenuItem saveProject;
    private javax.swing.JTextField searchBox;
    private javax.swing.JMenuItem signOutUser;
    private javax.swing.JTree sourceFolder;
    private javax.swing.JTabbedPane tags;
    private javax.swing.JMenu userMenu;
    private javax.swing.JScrollPane viewAllTags;
    private javax.swing.JMenuItem viewVersionHistory;
    private javax.swing.JTabbedPane views;
    // End of variables declaration//GEN-END:variables
}
