/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ApplicationStart.java
 *
 * Created on Oct 12, 2011, 8:27:01 PM
 */
package userinterface;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.*;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeEvent;
import javax.swing.tree.DefaultTreeCellRenderer;
import org.openide.awt.TabbedPaneFactory;
import it.cnr.imaa.essi.lablib.gui.checkboxtree.*;
import javax.swing.tree.TreePath;
import javax.swing.tree.TreeSelectionModel;
import model.*;
/**
 *
 * @author Brittany Nkounkou
 */
public class MainFrame extends JFrame implements PropertyChangeListener{
    private Project project;
    private User user;
    
    
    /** Creates new from ApplicationStart */
    public MainFrame() {
        //TODO  Make it so it asks for user/pass and the project to open
        
        //project = null;
        //user = null;
        
        user = new User("default", "default");
        project = new Project("defaultProject","defaultPath", user);
        Folder folder1 = project.createFolder(project.getMainFolder(), "TestFolder1");
        project.importSourceText("./QDA/TestTextFile.txt", folder1);
        
        helpViewIndex = -1;
        
        checkedElements = new DefaultCheckboxTreeCellRenderer();
        checkedElements.setOpenIcon(new ImageIcon(getClass().getResource("/userinterface/icons/Open Folder.png")));
        checkedElements.setClosedIcon(new ImageIcon(getClass().getResource("/userinterface/icons/Closed Folder.png")));
        checkedElements.setLeafIcon(new ImageIcon(getClass().getResource("/userinterface/icons/File.png")));
        
        checkedTags = new DefaultCheckboxTreeCellRenderer();
        checkedTags.setOpenIcon(new ImageIcon(getClass().getResource("/userinterface/icons/Open Tag Set.png")));
        checkedTags.setClosedIcon(new ImageIcon(getClass().getResource("/userinterface/icons/Closed Tag Set.png")));
        checkedTags.setLeafIcon(new ImageIcon(getClass().getResource("/userinterface/icons/Tag.png")));
        
        initComponents();
        
        project.addTagType(project.getRootTag(),"child");
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int w = (int) screenSize.getWidth();
        int h = (int) screenSize.getHeight();
        setBounds(w/10, h/10, w*4/5, h*3/4);
        projectData.requestFocusInWindow();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        applicationPane = new javax.swing.JSplitPane();
        projectData = new javax.swing.JSplitPane();
        repositoryWindow = new javax.swing.JPanel();
        repositoryLabel = new javax.swing.JLabel();
        repositoryTools = new javax.swing.JToolBar();
        importFile = new javax.swing.JButton();
        newFolder = new javax.swing.JButton();
        cutElement = new javax.swing.JButton();
        copyElement = new javax.swing.JButton();
        pasteElement = new javax.swing.JButton();
        renameElement = new javax.swing.JButton();
        deleteElement = new javax.swing.JButton();
        repositoryPane = new javax.swing.JScrollPane();
        repository = new javax.swing.JTree();
        tagsWindow = new javax.swing.JPanel();
        tagsLabel = new javax.swing.JLabel();
        tagsTools = new javax.swing.JToolBar();
        newTag = new javax.swing.JButton();
        newTagSet = new javax.swing.JButton();
        cutTag = new javax.swing.JButton();
        copyTag = new javax.swing.JButton();
        pasteTag = new javax.swing.JButton();
        renameTag = new javax.swing.JButton();
        deleteTag = new javax.swing.JButton();
        tagsPane = new javax.swing.JScrollPane();
        tags = new javax.swing.JTree();
        if (project != null && user != null) {
            tags = new javax.swing.JTree(project.getRootTag());
            tags.setRootVisible(true);
        }
        else {
            tags.setRootVisible(false);
        }

        DefaultTreeCellRenderer uncheckedTags = new DefaultTreeCellRenderer();
        uncheckedTags.setOpenIcon(new ImageIcon(getClass().getResource("/userinterface/icons/Open Tag Set.png")));
        uncheckedTags.setClosedIcon(new ImageIcon(getClass().getResource("/userinterface/icons/Closed Tag Set.png")));
        uncheckedTags.setLeafIcon(new ImageIcon(getClass().getResource("/userinterface/icons/Tag.png")));
        views = TabbedPaneFactory.createCloseButtonTabbedPane();
        newSearch = new javax.swing.JButton();
        applicationMenu = new javax.swing.JMenuBar();
        projectMenu = new javax.swing.JMenu();
        newProject = new javax.swing.JMenuItem();
        openProject = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        saveProject = new javax.swing.JMenuItem();
        saveAsProject = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mergeProject = new javax.swing.JMenuItem();
        viewVersionHistory = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        manageUsers = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        closeProject = new javax.swing.JMenuItem();
        userMenu = new javax.swing.JMenu();
        accountSettings = new javax.swing.JMenuItem();
        signInUser = new javax.swing.JMenuItem();
        signOutUser = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        helpContents = new javax.swing.JMenuItem();
        about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AppName");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(500, 300));
        setName(""); // NOI18N

        applicationPane.setDividerLocation(205);

        projectData.setDividerLocation(250);
        projectData.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        repositoryWindow.setLayout(new javax.swing.BoxLayout(repositoryWindow, javax.swing.BoxLayout.Y_AXIS));

        repositoryLabel.setText("Repository");
        repositoryWindow.add(repositoryLabel);

        if (project != null && user != null) {
            repositoryTools.setEnabled(true);
        }
        else {
            repositoryTools.setEnabled(false);
        }
        repositoryTools.setFloatable(false);
        repositoryTools.setRollover(true);
        repositoryTools.setAlignmentX(0.0F);

        importFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/icons/Import File.png"))); // NOI18N
        importFile.setToolTipText("Import File");
        importFile.setFocusable(false);
        importFile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        importFile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        importFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importFileActionPerformed(evt);
            }
        });
        repositoryTools.add(importFile);

        newFolder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/icons/New Folder.png"))); // NOI18N
        newFolder.setToolTipText("New Folder");
        newFolder.setFocusable(false);
        newFolder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newFolder.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        repositoryTools.add(newFolder);

        cutElement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/icons/Cut.png"))); // NOI18N
        cutElement.setToolTipText("Cut");
        cutElement.setFocusable(false);
        cutElement.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cutElement.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        repositoryTools.add(cutElement);

        copyElement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/icons/Copy.png"))); // NOI18N
        copyElement.setToolTipText("Copy");
        copyElement.setFocusable(false);
        copyElement.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        copyElement.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        repositoryTools.add(copyElement);

        pasteElement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/icons/Paste.png"))); // NOI18N
        pasteElement.setToolTipText("Paste");
        pasteElement.setFocusable(false);
        pasteElement.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pasteElement.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        repositoryTools.add(pasteElement);

        renameElement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/icons/Rename.png"))); // NOI18N
        renameElement.setToolTipText("Rename");
        renameElement.setFocusable(false);
        renameElement.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        renameElement.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        renameElement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renameElementActionPerformed(evt);
            }
        });
        repositoryTools.add(renameElement);

        deleteElement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/icons/Delete.png"))); // NOI18N
        deleteElement.setToolTipText("Delete");
        deleteElement.setFocusable(false);
        deleteElement.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteElement.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        repositoryTools.add(deleteElement);

        repositoryWindow.add(repositoryTools);

        repositoryPane.setAlignmentX(0.0F);

        if (project != null && user != null) {
            repository = new javax.swing.JTree(project.getMainFolder());
            repository.setRootVisible(true);
        }
        else {
            repository.setRootVisible(false);
        }

        DefaultTreeCellRenderer uncheckedElements = new DefaultTreeCellRenderer();
        uncheckedElements.setOpenIcon(new ImageIcon(getClass().getResource("/userinterface/icons/Open Folder.png")));
        uncheckedElements.setClosedIcon(new ImageIcon(getClass().getResource("/userinterface/icons/Closed Folder.png")));
        uncheckedElements.setLeafIcon(new ImageIcon(getClass().getResource("/userinterface/icons/File.png")));
        repository.setCellRenderer(uncheckedElements);
        repository.setEditable(true);
        repository.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        repository.setSelectionInterval(0, 0);
        repository.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                repositoryMousePressed(evt);
            }
        });
        repositoryPane.setViewportView(repository);

        repositoryWindow.add(repositoryPane);

        projectData.setTopComponent(repositoryWindow);

        tagsWindow.setLayout(new javax.swing.BoxLayout(tagsWindow, javax.swing.BoxLayout.Y_AXIS));

        tagsLabel.setText("Tags");
        tagsWindow.add(tagsLabel);

        if (project != null && user != null) {
            tagsTools.setEnabled(true);
        }
        else {
            tagsTools.setEnabled(false);
        }
        tagsTools.setFloatable(false);
        tagsTools.setRollover(true);
        tagsTools.setAlignmentX(0.0F);

        newTag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/icons/New Tag.png"))); // NOI18N
        newTag.setToolTipText("New Tag");
        newTag.setFocusable(false);
        newTag.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newTag.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tagsTools.add(newTag);

        newTagSet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/icons/New Tag Set.png"))); // NOI18N
        newTagSet.setToolTipText("New Tag Set");
        newTagSet.setFocusable(false);
        newTagSet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newTagSet.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tagsTools.add(newTagSet);

        cutTag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/icons/Cut.png"))); // NOI18N
        cutTag.setToolTipText("Cut");
        cutTag.setFocusable(false);
        cutTag.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cutTag.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tagsTools.add(cutTag);

        copyTag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/icons/Copy.png"))); // NOI18N
        copyTag.setToolTipText("Copy");
        copyTag.setFocusable(false);
        copyTag.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        copyTag.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tagsTools.add(copyTag);

        pasteTag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/icons/Paste.png"))); // NOI18N
        pasteTag.setToolTipText("Paste");
        pasteTag.setFocusable(false);
        pasteTag.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pasteTag.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tagsTools.add(pasteTag);

        renameTag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/icons/Rename.png"))); // NOI18N
        renameTag.setToolTipText("Rename");
        renameTag.setFocusable(false);
        renameTag.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        renameTag.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        renameTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renameTagActionPerformed(evt);
            }
        });
        tagsTools.add(renameTag);

        deleteTag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/icons/Delete.png"))); // NOI18N
        deleteTag.setToolTipText("Delete");
        deleteTag.setFocusable(false);
        deleteTag.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteTag.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tagsTools.add(deleteTag);

        tagsWindow.add(tagsTools);

        tagsPane.setAlignmentX(0.0F);

        tags.setCellRenderer(uncheckedTags);
        tags.setEditable(true);
        tags.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        tags.setSelectionInterval(0, 0);
        tagsPane.setViewportView(tags);

        tagsWindow.add(tagsPane);

        projectData.setRightComponent(tagsWindow);

        applicationPane.setLeftComponent(projectData);

        views.addPropertyChangeListener(TabbedPaneFactory.PROP_CLOSE, this);
        views.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                viewsStateChanged(evt);
            }
        });
        applicationPane.setRightComponent(views);

        if (project != null && user != null) {
            newSearch.setEnabled(true);
        }
        else {
            newSearch.setEnabled(false);
        }
        newSearch.setText("New Search");
        newSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSearchActionPerformed(evt);
            }
        });

        projectMenu.setText("Project");
        projectMenu.setFocusCycleRoot(true);
        projectMenu.setFocusPainted(true);

        newProject.setText("New");
        newProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProjectActionPerformed(evt);
            }
        });
        projectMenu.add(newProject);

        openProject.setText("Open");
        openProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openProjectActionPerformed(evt);
            }
        });
        projectMenu.add(openProject);
        projectMenu.add(jSeparator1);

        if (project != null && user != null) {
            saveProject.setEnabled(true);
        }
        else {
            saveProject.setEnabled(false);
        }
        saveProject.setText("Save");
        projectMenu.add(saveProject);

        if (project != null && user != null) {
            saveAsProject.setEnabled(true);
        }
        else {
            saveAsProject.setEnabled(false);
        }
        saveAsProject.setText("Save As");
        saveAsProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAsActionPerformed(evt);
            }
        });
        projectMenu.add(saveAsProject);
        projectMenu.add(jSeparator3);

        if (project != null && user != null) {
            mergeProject.setEnabled(true);
        }
        else {
            mergeProject.setEnabled(false);
        }
        mergeProject.setText("Merge");
        projectMenu.add(mergeProject);

        if (project != null && user != null) {
            viewVersionHistory.setEnabled(true);
        }
        else {
            viewVersionHistory.setEnabled(false);
        }
        viewVersionHistory.setText("View Version History");
        projectMenu.add(viewVersionHistory);
        projectMenu.add(jSeparator4);

        if (project != null && user != null && false/*TODO: is admin*/) {
            manageUsers.setEnabled(true);
        }
        else {
            manageUsers.setEnabled(false);
        }
        manageUsers.setText("Manage Users");
        manageUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUsersActionPerformed(evt);
            }
        });
        projectMenu.add(manageUsers);
        projectMenu.add(jSeparator2);

        if (project != null) {
            closeProject.setEnabled(true);
        }
        else {
            closeProject.setEnabled(false);
        }
        closeProject.setText("Close");
        closeProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXIT_ON_CLOSE(evt);
            }
        });
        projectMenu.add(closeProject);

        applicationMenu.add(projectMenu);

        if (project != null) {
            userMenu.setEnabled(true);
        }
        else {
            userMenu.setEnabled(false);
        }
        userMenu.setText("User");
        userMenu.setFocusCycleRoot(true);
        userMenu.setFocusPainted(true);

        accountSettings.setText("Account Settings");
        accountSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountSettingsActionPerformed(evt);
            }
        });
        userMenu.add(accountSettings);

        if (project != null && user == null) {
            signInUser.setEnabled(true);
        }
        else {
            signInUser.setEnabled(false);
        }
        signInUser.setText("Sign In");
        signInUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInUserActionPerformed(evt);
            }
        });
        userMenu.add(signInUser);

        if (project != null && user != null) {
            signOutUser.setEnabled(true);
        }
        else {
            signOutUser.setEnabled(false);
        }
        signOutUser.setText("Sign Out");
        userMenu.add(signOutUser);
        signOutUser.getAccessibleContext().setAccessibleName("");

        applicationMenu.add(userMenu);

        helpMenu.setText("Help");
        helpMenu.setFocusCycleRoot(true);
        helpMenu.setFocusPainted(true);

        helpContents.setText("Help Contents");
        helpContents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpContentsActionPerformed(evt);
            }
        });
        helpMenu.add(helpContents);

        about.setText("About");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        helpMenu.add(about);

        applicationMenu.add(helpMenu);

        applicationMenu.add(Box.createHorizontalGlue());
        applicationMenu.add(newSearch);

        setJMenuBar(applicationMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(applicationPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(applicationPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void helpContentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpContentsActionPerformed
    if (helpViewIndex == -1) {
        addView(new HelpView());
        helpViewIndex = views.getSelectedIndex();
    }
    else {
        views.setSelectedIndex(helpViewIndex);
    }
    views.getSelectedComponent().requestFocusInWindow();
}//GEN-LAST:event_helpContentsActionPerformed

private void newProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProjectActionPerformed
    NewProjectDialog npd = new NewProjectDialog(this);
    npd.setVisible(true);
    if (npd.hasResults()) {
        String name = npd.getProjectName();
        String path = npd.getProjectPath();
        String admin = npd.getAdministrator();
        char[] password = npd.getPassword();
        //TODO
    }
}//GEN-LAST:event_newProjectActionPerformed

private void manageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUsersActionPerformed
    ManageUsersDialog mud = new ManageUsersDialog(this);
    mud.setVisible(true);
}//GEN-LAST:event_manageUsersActionPerformed

private void accountSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountSettingsActionPerformed
    AccountSettingsDialog asd = new AccountSettingsDialog(this);
    asd.setVisible(true);
}//GEN-LAST:event_accountSettingsActionPerformed

private void signInUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInUserActionPerformed
    SignInDialog sid = new SignInDialog(this, project);
    sid.setVisible(true);
}//GEN-LAST:event_signInUserActionPerformed

private void EXIT_ON_CLOSE(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXIT_ON_CLOSE
// TODO add your handling code here:
    System.exit(0); // Exit the application
}//GEN-LAST:event_EXIT_ON_CLOSE

private void openProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openProjectActionPerformed
    OpenProjectDialog opd = new OpenProjectDialog(this);
    opd.setVisible(true);
    if(opd.hasResults()) {
        String user = opd.getUserName();
        char[] password = opd.getPassword();
    }
}//GEN-LAST:event_openProjectActionPerformed

private void SaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAsActionPerformed
    SaveAsProjectDialog sap = new SaveAsProjectDialog(this);
    sap.setVisible(true);
    if(sap.hasResults()) {
        String location = sap.getSaveLocation();
    }
}//GEN-LAST:event_SaveAsActionPerformed

private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
    AboutProjectDialog apd = new AboutProjectDialog(this);
    apd.setVisible(true);
}//GEN-LAST:event_aboutActionPerformed

    private void viewsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_viewsStateChanged
        View view = (View) views.getSelectedComponent();
        if (view instanceof SearchView) {
            repositoryPane.setViewportView(((SearchView) view).getFilesTree());
            tagsPane.setViewportView(((SearchView) view).getTagsTree());
        }
        else {
            repositoryPane.setViewportView(repository);
            if (view instanceof SourceTextView) {
                tagsPane.setViewportView(((SourceTextView) view).getTagsTree());
            }
            else {
                tagsPane.setViewportView(tags);
            }
        }
    }//GEN-LAST:event_viewsStateChanged

    private void newSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSearchActionPerformed
        CheckboxTree rep = new CheckboxTree(repository.getModel());
        rep.setCellRenderer(checkedElements);
        rep.setEditable(true);
        rep.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        rep.setSelectionInterval(0, 0);
        rep.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent evt) {
                repositoryMousePressed(evt);
            }
        });
        
        CheckboxTree tag = new CheckboxTree(tags.getModel());
        tags.setCellRenderer(checkedTags);
        tags.setEditable(true);
        tags.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        tags.setSelectionInterval(0, 0);
        addView(new SearchView("New Search", rep, tag));
    }//GEN-LAST:event_newSearchActionPerformed

    private void repositoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_repositoryMousePressed
        JTree rep = (JTree) repositoryPane.getViewport().getView();
        int selRow = rep.getRowForLocation(evt.getX(), evt.getY());
        TreePath alpha = rep.getSelectionPath();
        String beta = alpha.getLastPathComponent().toString();
        //check if node
        if(beta.contains("/")) { //it is a node
            int start = beta.lastIndexOf("/") + 1;
            int end = beta.lastIndexOf(".");
            String filename = beta.substring(start, end);
            if(selRow != -1) {
            if(evt.getClickCount() == 2 ) {
                CheckboxTree tag = new CheckboxTree();
                tag.setCellRenderer(checkedTags);
                tag.setSelectionModel(null);
                //TODO
                //addView(new SourceTextView(filename, tag));
            }
        }
            
        } else {
            // Do nothing since a node wasn't selected
        }

    }//GEN-LAST:event_repositoryMousePressed

    private void renameElementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renameElementActionPerformed
        JTree rep = (JTree) repositoryPane.getViewport().getView();
        TreePath path = rep.getSelectionPath();
        if (path == null) {
            ErrorDialog ed = new ErrorDialog(this, "Please select a File or Folder to rename.");
            ed.setVisible(true);
        }
        else {
            rep.startEditingAtPath(rep.getSelectionPath());
        }
    }//GEN-LAST:event_renameElementActionPerformed

    private void renameTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renameTagActionPerformed
        TreePath path = tags.getSelectionPath();
        if (path == null) {
            ErrorDialog ed = new ErrorDialog(this, "Please select a Tag or Tag Set to rename.");
            ed.setVisible(true);
        }
        else {
            tags.startEditingAtPath(tags.getSelectionPath());
        }
    }//GEN-LAST:event_renameTagActionPerformed

    private void importFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importFileActionPerformed
        
    }//GEN-LAST:event_importFileActionPerformed

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        int indexToDelete = views.indexOfComponent((java.awt.Component)evt.getNewValue());
        if (helpViewIndex == indexToDelete) {
            helpViewIndex = -1;
        }
        views.removeTabAt(indexToDelete);
    }

    public void addView(View v) {
        views.addTab(v.getAbbrv(), null, v, v.getTitle());
        views.setSelectedIndex(views.indexOfComponent(v));
    }
    
    private int helpViewIndex;
    private DefaultCheckboxTreeCellRenderer checkedElements = new DefaultCheckboxTreeCellRenderer();
    private DefaultCheckboxTreeCellRenderer checkedTags = new DefaultCheckboxTreeCellRenderer();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem about;
    private javax.swing.JMenuItem accountSettings;
    private javax.swing.JMenuBar applicationMenu;
    private javax.swing.JSplitPane applicationPane;
    private javax.swing.JMenuItem closeProject;
    private javax.swing.JButton copyElement;
    private javax.swing.JButton copyTag;
    private javax.swing.JButton cutElement;
    private javax.swing.JButton cutTag;
    private javax.swing.JButton deleteElement;
    private javax.swing.JButton deleteTag;
    private javax.swing.JMenuItem helpContents;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton importFile;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenuItem manageUsers;
    private javax.swing.JMenuItem mergeProject;
    private javax.swing.JButton newFolder;
    private javax.swing.JMenuItem newProject;
    private javax.swing.JButton newSearch;
    private javax.swing.JButton newTag;
    private javax.swing.JButton newTagSet;
    private javax.swing.JMenuItem openProject;
    private javax.swing.JButton pasteElement;
    private javax.swing.JButton pasteTag;
    private javax.swing.JSplitPane projectData;
    private javax.swing.JMenu projectMenu;
    private javax.swing.JButton renameElement;
    private javax.swing.JButton renameTag;
    private javax.swing.JTree repository;
    private javax.swing.JLabel repositoryLabel;
    private javax.swing.JScrollPane repositoryPane;
    private javax.swing.JToolBar repositoryTools;
    private javax.swing.JPanel repositoryWindow;
    private javax.swing.JMenuItem saveAsProject;
    private javax.swing.JMenuItem saveProject;
    private javax.swing.JMenuItem signInUser;
    private javax.swing.JMenuItem signOutUser;
    private javax.swing.JTree tags;
    private javax.swing.JLabel tagsLabel;
    private javax.swing.JScrollPane tagsPane;
    private javax.swing.JToolBar tagsTools;
    private javax.swing.JPanel tagsWindow;
    private javax.swing.JMenu userMenu;
    private javax.swing.JMenuItem viewVersionHistory;
    private javax.swing.JTabbedPane views;
    // End of variables declaration//GEN-END:variables
}
